# Generated by Django 6.0.3 on 2026-03-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componenti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaAcquisti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('creata_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaEsperienza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('professore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoceListaAcquisti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_da_acquistare', models.PositiveIntegerField(default=1)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componenti.componente')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.listaacquisti')),
            ],
        ),
        migrations.AddField(
            model_name='listaacquisti',
            name='componenti',
            field=models.ManyToManyField(through='liste.VoceListaAcquisti', to='componenti.componente'),
        ),
        migrations.CreateModel(
            name='VoceListaEsperienza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_necessaria', models.PositiveIntegerField(default=1)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componenti.componente')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.listaesperienza')),
            ],
        ),
        migrations.AddField(
            model_name='listaesperienza',
            name='componenti',
            field=models.ManyToManyField(through='liste.VoceListaEsperienza', to='componenti.componente'),
        ),
    ]
