# Generated by Django 6.0.3 on 2026-03-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(max_length=50)),
                ('sezione', models.CharField(max_length=50)),
                ('cassetto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figli', to='componenti.famiglia')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('link_datasheet', models.URLField(blank=True)),
                ('quantita', models.PositiveIntegerField(default=0)),
                ('quantita_minima', models.PositiveIntegerField(default=0)),
                ('is_scorta', models.BooleanField(default=False)),
                ('famiglia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='componenti.famiglia')),
                ('locazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='componenti.locazione')),
                ('tag', models.ManyToManyField(blank=True, to='componenti.tag')),
            ],
        ),
    ]
