# Generated by Django 6.0.5 on 2026-05-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'verbose_name_plural': 'Componenti'},
        ),
        migrations.AlterModelOptions(
            name='famiglia',
            options={'verbose_name_plural': 'Famiglie'},
        ),
        migrations.AlterModelOptions(
            name='locazione',
            options={'verbose_name_plural': 'Locazioni'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tag'},
        ),
    ]
