# Generated by Django 6.0.5 on 2026-05-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'verbose_name_plural': 'Movimenti'},
        ),
    ]
